title: Micro blog
email: toto@bille.dev
description: >-
  This blog is a set of recent discoveries that I made. I try to write
  small articles with cool tips & tricks.
baseurl: ""
url: "https://blog.bille.dev"

collections:
  posts:
    permalink: /:slug

plugins:
  - jekyll-feed
