title: Micro blog
email: toto@bille.dev
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.bille.dev" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: totostache
github_username:  tbille

collections:
  posts:
    permalink: /:slug

plugins:
  - jekyll-feed
